// ===== CHARACTER SVGs =====
const CHAR_SVG={
전사:{type:'sprite',frames:8,
  idle:{src:'img/warrior-idle.png',w:89,h:128,tw:712},
  walk:{src:'img/warrior-walk.png',w:96,h:128,tw:768},
  slash:{src:'img/warrior-slash.png',w:67,h:128,tw:536},
  jab:{src:'img/warrior-jab.png',w:62,h:128,tw:496},
  block:{src:'img/warrior-block.png',w:93,h:128,tw:744},
  death:{src:'img/warrior-death.png',w:131,h:128,tw:1048}},
마법사:{type:'sprite',frames:8,
  idle:{src:'img/wizard-idle.png',w:91,h:128,tw:728},
  walk:{src:'img/wizard-walk.png',w:92,h:128,tw:736},
  cast:{src:'img/wizard-cast.png',w:56,h:128,tw:448},
  slash:{src:'img/wizard-slash.png',w:64,h:128,tw:512},
  block:{src:'img/wizard-block.png',w:112,h:128,tw:896},
  death:{src:'img/wizard-death.png',w:137,h:128,tw:1096}},
거너:{type:'sprite',frames:8,
  idle:{src:'img/gunner-idle.png',w:88,h:128,tw:704},
  walk:{src:'img/gunner-walk.png',w:92,h:128,tw:736},
  shot:{src:'img/gunner-shot.png',w:106,h:128,tw:848},
  slash:{src:'img/gunner-slash.png',w:114,h:128,tw:912},
  block:{src:'img/gunner-block.png',w:85,h:128,tw:680},
  death:{src:'img/gunner-death.png',w:131,h:128,tw:1048}},
궁수:{type:'sprite',frames:8,
  idle:{src:'img/archer-idle.png',w:96,h:128,tw:768},
  walk:{src:'img/archer-walk.png',w:98,h:128,tw:784},
  shot:{src:'img/archer-shot.png',w:98,h:128,tw:784},
  slash:{src:'img/archer-slash.png',w:117,h:128,tw:936},
  block:{src:'img/archer-block.png',w:91,h:128,tw:728},
  death:{src:'img/archer-death.png',w:140,h:128,tw:1120}},
도적:{type:'sprite',frames:8,
  idle:{src:'img/thief-idle.png',w:94,h:128,tw:752},
  slash:{src:'img/thief-slash.png',w:109,h:128,tw:872},
  jab:{src:'img/thief-jab.png',w:126,h:128,tw:1008},
  block:{src:'img/thief-block.png',w:99,h:128,tw:792},
  death:{src:'img/thief-death.png',w:131,h:128,tw:1048}},
성기사:{type:'sprite',frames:8,
  idle:{src:'img/paladin-idle.png',w:77,h:128,tw:616},
  slash:{src:'img/paladin-slash.png',w:106,h:128,tw:848},
  cast:{src:'img/paladin-cast.png',w:104,h:128,tw:832},
  block:{src:'img/paladin-block.png',w:79,h:128,tw:632},
  death:{src:'img/paladin-death.png',w:134,h:128,tw:1072}},
엔지니어:{type:'sprite',frames:8,
  idle:{src:'img/engineer-idle.png',w:83,h:128,tw:664},
  shot:{src:'img/engineer-shot.png',w:109,h:128,tw:872},
  slash:{src:'img/engineer-slash.png',w:105,h:128,tw:840},
  block:{src:'img/engineer-block.png',w:95,h:128,tw:760},
  death:{src:'img/engineer-death.png',w:148,h:128,tw:1184}},
드루이드:{type:'sprite',frames:8,
  idle:{src:'img/druid-idle.png',w:85,h:128,tw:680},
  cast:{src:'img/druid-cast.png',w:57,h:128,tw:456},
  slash:{src:'img/druid-slash.png',w:64,h:128,tw:512},
  block:{src:'img/druid-block.png',w:96,h:128,tw:768},
  death:{src:'img/druid-death.png',w:138,h:128,tw:1104}},
소환사:{type:'sprite',frames:8,
  idle:{src:'img/summoner-idle.png',w:92,h:128,tw:736},
  cast:{src:'img/summoner-cast.png',w:65,h:128,tw:520},
  slash:{src:'img/summoner-slash.png',w:91,h:128,tw:728},
  block:{src:'img/summoner-block.png',w:55,h:128,tw:440},
  death:{src:'img/summoner-death.png',w:152,h:128,tw:1216}},
흑마법사:{type:'sprite',frames:8,
  idle:{src:'img/black_wizard-idle.png',w:75,h:128,tw:600},
  cast:{src:'img/black_wizard-cast.png',w:53,h:128,tw:424},
  slash:{src:'img/black_wizard-slash.png',w:55,h:128,tw:440},
  block:{src:'img/black_wizard-block.png',w:91,h:128,tw:728},
  death:{src:'img/black_wizard-death.png',w:139,h:128,tw:1112}},
힐러:{type:'sprite',frames:8,
  idle:{src:'img/healer-idle.png',w:85,h:128,tw:680},
  cast:{src:'img/healer-cast.png',w:52,h:128,tw:416},
  slash:{src:'img/healer-slash.png',w:61,h:128,tw:488},
  block:{src:'img/healer-block.png',w:92,h:128,tw:736},
  death:{src:'img/healer-death.png',w:132,h:128,tw:1056}}
};

// ===== GAME DATA =====
const CLASSES={
거너:{color:'#22c55e',glow:'#22c55e',weapon:'🔫',bodyColor:'linear-gradient(180deg,#1a5c2a,#0f3d1a)',desc:'원거리 딜러. 총과 폭발물로 적을 섬멸한다.',baseHP:90,baseATK:18,baseDEF:6,
skills:[
{name:'샷건',icon:'💥',desc:'근거리 산탄 — 높은 데미지',dmg:30},
{name:'기관총',icon:'🔫',desc:'연사 공격 — 다중 타격',dmg:12,hits:3},
{name:'수류탄',icon:'💣',desc:'AoE 폭발 — 광역 데미지',dmg:22,aoe:true},
{name:'스팀팩',icon:'💉',desc:'공속 버프 — ATK +30%',buff:true,dmg:0},
{name:'러시안룰렛',icon:'🎰',desc:'HP 30% 이하 시 폭딜',dmg:50},
{name:'네이팜탄',icon:'🔥',desc:'지속 화염 — DoT 데미지',dmg:15,dot:true},
{name:'관통탄',icon:'🎯',desc:'관통 사격 — 방어 무시',dmg:28},
{name:'산탄폭풍',icon:'🌪️',desc:'360도 전체 공격',dmg:20,aoe:true},
{name:'드론포격',icon:'🤖',desc:'자동 드론 소환 공격',dmg:18},
{name:'저격',icon:'🔭',desc:'원거리 초고데미지 단일 타격',dmg:45}],
passives:[
{name:'치명타 +15%',icon:'💀',desc:'치명타 확률 15% 증가'},
{name:'쿨타임 -20%',icon:'⏱️',desc:'스킬 쿨타임 20% 감소'},
{name:'50% 두발 시전',icon:'🎲',desc:'50% 확률로 스킬 2회 시전'},
{name:'AoE +30%',icon:'💫',desc:'광역 스킬 범위 30% 증가'},
{name:'딸피 적 +50%',icon:'☠️',desc:'HP 낮은 적에게 50% 추가 데미지'},
{name:'5타 추가탄',icon:'🔄',desc:'5번째 공격마다 추가탄 발사'}]},
마법사:{color:'#4a9eff',glow:'#4a9eff',weapon:'🪄',bodyColor:'linear-gradient(180deg,#1a3a6c,#0f1f3d)',desc:'마법 딜러. 원소 마법으로 전장을 지배한다.',baseHP:80,baseATK:22,baseDEF:5,
skills:[
{name:'파이어볼',icon:'🔥',desc:'화염 폭발 — 단일 고데미지',dmg:28},
{name:'아이스노바',icon:'❄️',desc:'AoE 빙결 — 광역+둔화',dmg:20,aoe:true},
{name:'입자와 파동',icon:'⚛️',desc:'50/50 단일 또는 범위 공격',dmg:25},
{name:'블레이즈',icon:'🔥',desc:'화염 자취 — 지속 데미지',dmg:15,dot:true},
{name:'사건의 지평선',icon:'🌀',desc:'중력장 — 적 속박',dmg:18},
{name:'얼음방패',icon:'🧊',desc:'5초 무적 — 방어 스킬',buff:true,dmg:0},
{name:'체인라이트닝',icon:'⚡',desc:'5연쇄 번개 공격',dmg:14,hits:5},
{name:'메테오',icon:'☄️',desc:'대형 AoE — 최강 광역기',dmg:35,aoe:true},
{name:'텔레포트',icon:'✨',desc:'순간이동 + 데미지',dmg:20},
{name:'마나폭발',icon:'💜',desc:'HP 희생 폭딜 — 고위험 고보상',dmg:55}],
passives:[
{name:'빙결 얼음화살',icon:'🏹',desc:'빙결된 적에게 추가 얼음화살'},
{name:'쿨타임 -50%',icon:'⏱️',desc:'스킬 쿨타임 50% 대폭 감소'},
{name:'불타는 적 +30%',icon:'🔥',desc:'화상 상태 적에게 30% 추가 데미지'},
{name:'킬 후 무소비',icon:'💀',desc:'킬 후 3초간 마나 소비 없음'},
{name:'2속성 폭발',icon:'💥',desc:'2가지 속성 연속 히트 시 보너스 폭발'},
{name:'연쇄폭발 30%',icon:'🔗',desc:'AoE 킬 시 30% 확률 연쇄폭발'}]},
전사:{color:'#ef4444',glow:'#ef4444',weapon:'⚔️',bodyColor:'linear-gradient(180deg,#6c1a1a,#3d0f0f)',desc:'근접 탱커/딜러. 강인한 방어와 강력한 근접 공격.',baseHP:120,baseATK:15,baseDEF:10,
skills:[
{name:'검기',icon:'🗡️',desc:'원거리 검파 — 중거리 공격',dmg:24},
{name:'칼날 복제',icon:'👥',desc:'분신 공격 — 2회 타격',dmg:16,hits:2},
{name:'휠윈드',icon:'🌀',desc:'회전 공격 — 광역 데미지',dmg:22,aoe:true},
{name:'회전칼날',icon:'💫',desc:'궤도 칼날 — 지속 데미지',dmg:14,dot:true},
{name:'스톰프',icon:'🦶',desc:'스턴 — 적 행동 불가',dmg:18},
{name:'돌진',icon:'🏃',desc:'차지+넉백 — 돌격 공격',dmg:26},
{name:'방패올리기',icon:'🛡️',desc:'방어+반격 — 피해 감소',buff:true,dmg:0},
{name:'지진',icon:'🌋',desc:'직선 균열 — 범위 공격',dmg:28,aoe:true},
{name:'전투의 함성',icon:'📯',desc:'ATK +30% 버프',buff:true,dmg:0},
{name:'처형',icon:'⚰️',desc:'딸피 적 즉사급 — 마무리기',dmg:60}],
passives:[
{name:'피흡 20%',icon:'🩸',desc:'데미지의 20%를 HP로 회복'},
{name:'반사뎀 100%',icon:'🪞',desc:'받는 데미지 100% 반사'},
{name:'HP +40%',icon:'💪',desc:'최대 HP 40% 증가'},
{name:'딸피 DEF +50%',icon:'🛡️',desc:'HP 20% 이하 시 DEF 50% 증가'},
{name:'낮은HP=높은ATK',icon:'😤',desc:'HP가 낮을수록 ATK 증가 (최대 +50%)'},
{name:'10피격 완전방어',icon:'🔰',desc:'10번 피격마다 완전 방어'}]},
궁수:{color:'#16a34a',glow:'#16a34a',weapon:'🏹',bodyColor:'linear-gradient(180deg,#1a4a2a,#0f2d1a)',desc:'원거리 딜러. 빠른 화살과 정밀 사격으로 적을 관통한다.',baseHP:85,baseATK:20,baseDEF:5,
skills:[
{name:'속사',icon:'🏹',desc:'빠른 연속 사격 — 3회 타격',dmg:12,hits:3},
{name:'관통화살',icon:'🎯',desc:'방어 무시 — 일직선 관통',dmg:30},
{name:'화살비',icon:'🌧️',desc:'AoE 화살 — 광역 데미지',dmg:20,aoe:true},
{name:'독화살',icon:'☠️',desc:'독 부여 — 지속 데미지',dmg:14,dot:true},
{name:'올가미',icon:'🪢',desc:'속박 — 적 이동 불가',dmg:16},
{name:'폭발화살',icon:'💣',desc:'착탄 폭발 — 범위 데미지',dmg:24,aoe:true},
{name:'매의 눈',icon:'🦅',desc:'집중 — 치명타 100%',buff:true,dmg:0},
{name:'이중사격',icon:'🎯',desc:'2발 동시 발사 — 강력 단일기',dmg:36},
{name:'구르기',icon:'🤸',desc:'회피+후방 사격',dmg:18},
{name:'저격',icon:'🔭',desc:'풀 차지 초고데미지 — 마무리기',dmg:55}],
passives:[
{name:'치명타 +20%',icon:'💀',desc:'치명타 확률 20% 증가'},
{name:'거리 비례 딜',icon:'📏',desc:'원거리일수록 데미지 증가 (최대 +40%)'},
{name:'연속킬 ATK+',icon:'🔥',desc:'연속 처치 시 ATK 15% 누적'},
{name:'화살 관통',icon:'➡️',desc:'화살이 적을 관통해 뒤의 적에게도 데미지'},
{name:'약점 사격',icon:'🎯',desc:'치명타 시 DEF 30% 무시'},
{name:'5타 폭발',icon:'💥',desc:'5번째 화살에 폭발 효과 추가'}]},
도적:{color:'#a855f7',glow:'#a855f7',weapon:'🗡️',bodyColor:'linear-gradient(180deg,#3d1a5c,#1f0f3d)',desc:'근접 암살자. 은신과 기습으로 치명적인 한 방을 노린다.',baseHP:75,baseATK:24,baseDEF:4,
skills:[
{name:'백스탭',icon:'🔪',desc:'기습 — 치명타 보장',dmg:35},
{name:'이중단검',icon:'⚔️',desc:'양손 난타 — 4회 타격',dmg:10,hits:4},
{name:'독연막',icon:'💨',desc:'AoE 독안개 — 범위+DoT',dmg:16,aoe:true,dot:true},
{name:'그림자 밟기',icon:'👤',desc:'순간이동 — 기습 공격',dmg:28},
{name:'은신',icon:'🫥',desc:'투명화 — 회피율 100%',buff:true,dmg:0},
{name:'출혈 베기',icon:'🩸',desc:'출혈 부여 — 지속 데미지',dmg:18,dot:true},
{name:'급소 가격',icon:'💀',desc:'방어 무시 — 크리 데미지 2배',dmg:32},
{name:'분신술',icon:'👥',desc:'분신 3체 — 각자 공격',dmg:12,hits:3},
{name:'연막탈출',icon:'💨',desc:'회피+ATK 버프',buff:true,dmg:0},
{name:'암살',icon:'☠️',desc:'HP 30% 이하 즉사 — 마무리기',dmg:60}],
passives:[
{name:'치명타 +25%',icon:'💀',desc:'치명타 확률 25% 증가'},
{name:'킬 후 은신',icon:'🫥',desc:'처치 후 3초 은신'},
{name:'독 강화',icon:'☠️',desc:'독 데미지 50% 증가'},
{name:'회피 +20%',icon:'💫',desc:'회피율 20% 증가'},
{name:'배후 공격 +50%',icon:'🔪',desc:'기습 공격 시 50% 추가 데미지'},
{name:'연속 암살',icon:'⚡',desc:'킬 후 즉시 다음 공격 가능'}]},
성기사:{color:'#fbbf24',glow:'#fbbf24',weapon:'⚜️',bodyColor:'linear-gradient(180deg,#6c5a1a,#3d330f)',desc:'탱커/힐러 하이브리드. 신성한 힘으로 아군을 보호한다.',baseHP:130,baseATK:14,baseDEF:12,
skills:[
{name:'심판의 검',icon:'⚔️',desc:'신성 데미지 — 언데드 특효',dmg:26},
{name:'성스러운 방패',icon:'🛡️',desc:'방어+힐 — 아군 보호',buff:true,dmg:0},
{name:'성스러운 빛',icon:'✨',desc:'AoE 신성 데미지',dmg:22,aoe:true},
{name:'축복',icon:'🙏',desc:'파티 ATK +20% 버프',buff:true,dmg:0},
{name:'정의의 철퇴',icon:'🔨',desc:'스턴 + 높은 데미지',dmg:30},
{name:'신성 보호막',icon:'💛',desc:'5초 무적 — 피해 완전 차단',buff:true,dmg:0},
{name:'응보',icon:'⚡',desc:'받은 피해 200% 되돌려줌',dmg:0},
{name:'정화',icon:'💫',desc:'디버프 제거 + 힐',buff:true,dmg:0},
{name:'신성 돌진',icon:'🏇',desc:'돌격 + 넉백 + 데미지',dmg:28},
{name:'천벌',icon:'🌩️',desc:'신성 심판 — 최강 단일기',dmg:50}],
passives:[
{name:'피격 시 힐',icon:'💚',desc:'피격 시 10% 확률 HP 회복'},
{name:'DEF +30%',icon:'🛡️',desc:'방어력 30% 증가'},
{name:'아군 보호막',icon:'💛',desc:'파티원 피격 시 대신 받기'},
{name:'신성 반격',icon:'⚡',desc:'방어 시 50% 확률 반격'},
{name:'불사',icon:'💀',desc:'치명상 시 1회 부활 (HP 30%)'},
{name:'축복 강화',icon:'✨',desc:'버프 지속시간 50% 증가'}]},
엔지니어:{color:'#f97316',glow:'#f97316',weapon:'🔧',bodyColor:'linear-gradient(180deg,#5c3a1a,#3d250f)',desc:'기계 전문가. 터렛과 장치로 전장을 지배한다.',baseHP:95,baseATK:16,baseDEF:8,
skills:[
{name:'터렛 설치',icon:'🤖',desc:'자동 포탑 — 지속 공격',dmg:14,dot:true},
{name:'지뢰',icon:'💣',desc:'함정 설치 — 밟으면 폭발',dmg:28},
{name:'화염방사기',icon:'🔥',desc:'AoE 근거리 화염',dmg:22,aoe:true},
{name:'전자충격',icon:'⚡',desc:'스턴 + 데미지',dmg:20},
{name:'수리',icon:'🔧',desc:'HP 회복 — 자가 수리',buff:true,dmg:0},
{name:'로켓런처',icon:'🚀',desc:'고데미지 광역 — 쿨타임 긴',dmg:32,aoe:true},
{name:'보호막 장치',icon:'🔰',desc:'DEF +50% 버프',buff:true,dmg:0},
{name:'드론',icon:'🛸',desc:'공격 드론 소환 — 3연타',dmg:12,hits:3},
{name:'과부하',icon:'💥',desc:'장치 전체 폭파 — 설치물 비례 데미지',dmg:40},
{name:'메카닉 아머',icon:'🦾',desc:'강화 외골격 — ATK/DEF 대폭 증가',buff:true,dmg:0}],
passives:[
{name:'터렛 강화',icon:'🤖',desc:'설치물 데미지 30% 증가'},
{name:'자동 수리',icon:'🔧',desc:'매 턴 HP 5% 자동 회복'},
{name:'폭발 범위+',icon:'💣',desc:'폭발 범위 40% 증가'},
{name:'장치 쿨감',icon:'⏱️',desc:'설치 스킬 쿨타임 30% 감소'},
{name:'방어탑 반격',icon:'🏗️',desc:'터렛이 공격받으면 반격'},
{name:'긴급 탈출',icon:'🪂',desc:'HP 20% 이하 시 자동 보호막'}]},
드루이드:{color:'#059669',glow:'#059669',weapon:'🌿',bodyColor:'linear-gradient(180deg,#1a5c3a,#0f3d25)',desc:'자연의 수호자. 변신과 자연 마법으로 싸운다.',baseHP:100,baseATK:17,baseDEF:8,
skills:[
{name:'덩굴 채찍',icon:'🌿',desc:'자연 공격 — 속박 효과',dmg:22},
{name:'곰 변신',icon:'🐻',desc:'탱커 모드 — DEF 2배',buff:true,dmg:0},
{name:'늑대 변신',icon:'🐺',desc:'딜러 모드 — ATK 2배',buff:true,dmg:0},
{name:'가시덤불',icon:'🌹',desc:'AoE 반사 장판',dmg:18,aoe:true},
{name:'자연의 힘',icon:'🌳',desc:'HP 대량 회복',buff:true,dmg:0},
{name:'벌떼',icon:'🐝',desc:'다중 타격 — 5회',dmg:8,hits:5},
{name:'지진',icon:'🌋',desc:'대지 광역 공격',dmg:26,aoe:true},
{name:'회복의 바람',icon:'🍃',desc:'파티 전체 힐',buff:true,dmg:0},
{name:'야수 소환',icon:'🦁',desc:'야수 동료 소환 — 3턴 공격',dmg:20},
{name:'자연의 분노',icon:'⛈️',desc:'폭풍 — 최강 광역기',dmg:42,aoe:true}],
passives:[
{name:'재생',icon:'💚',desc:'매 턴 HP 8% 자동 회복'},
{name:'변신 강화',icon:'🐻',desc:'변신 시 스탯 보너스 50% 증가'},
{name:'자연 친화',icon:'🌿',desc:'자연 스킬 데미지 25% 증가'},
{name:'야생 본능',icon:'🐺',desc:'HP 50% 이하 시 ATK +30%'},
{name:'생명의 씨앗',icon:'🌱',desc:'킬 시 HP 15% 회복'},
{name:'대지의 축복',icon:'🌍',desc:'DEF +20%, 이동속도 +15%'}]},
소환사:{color:'#7c3aed',glow:'#7c3aed',weapon:'📜',bodyColor:'linear-gradient(180deg,#3d1a6c,#250f4a)',desc:'소환술사. 강력한 소환수와 함께 싸운다.',baseHP:70,baseATK:12,baseDEF:5,
skills:[
{name:'임프 소환',icon:'👹',desc:'소형 악마 소환 — 지속 공격',dmg:14,dot:true},
{name:'골렘 소환',icon:'🗿',desc:'방어 골렘 — 파티 DEF+',buff:true,dmg:0},
{name:'정령 폭발',icon:'💜',desc:'정령 자폭 — 고데미지',dmg:32},
{name:'소환수 강화',icon:'⬆️',desc:'소환수 ATK +50%',buff:true,dmg:0},
{name:'영혼 화살',icon:'👻',desc:'원거리 영혼 공격',dmg:24},
{name:'지옥의 문',icon:'🌀',desc:'AoE 악마 소환 — 광역',dmg:22,aoe:true},
{name:'생명 흡수',icon:'🩸',desc:'적 HP 흡수 — 힐+딜',dmg:20},
{name:'피닉스 소환',icon:'🔥',desc:'불사조 소환 — 광역 화염',dmg:28,aoe:true},
{name:'저주',icon:'💀',desc:'적 약화 — DEF -50%',dmg:16},
{name:'드래곤 소환',icon:'🐉',desc:'최강 소환수 — 궁극기',dmg:55}],
passives:[
{name:'소환수 +1',icon:'👥',desc:'소환수 최대 수 1 증가'},
{name:'소환수 반격',icon:'⚡',desc:'소환수 피격 시 반격'},
{name:'영혼 수확',icon:'💀',desc:'킬 시 소환수 강화'},
{name:'마나 재생',icon:'💜',desc:'매 턴 마나 10% 회복'},
{name:'소환수 치명타',icon:'💥',desc:'소환수 치명타 +20%'},
{name:'불사 소환수',icon:'💛',desc:'소환수 1회 부활'}]},
흑마법사:{color:'#dc2626',glow:'#dc2626',weapon:'💀',bodyColor:'linear-gradient(180deg,#4a0f0f,#2d0808)',desc:'어둠의 마법사. HP를 대가로 강력한 저주와 흑마법을 사용한다.',baseHP:75,baseATK:25,baseDEF:4,
skills:[
{name:'어둠의 화살',icon:'🖤',desc:'암흑 투사체 — 단일 고딜',dmg:30},
{name:'생명 흡수',icon:'🩸',desc:'HP 흡수 공격 — 힐+딜',dmg:22},
{name:'저주의 장막',icon:'💀',desc:'AoE 저주 — 범위+약화',dmg:20,aoe:true},
{name:'영혼 폭발',icon:'👻',desc:'HP 소모 20% — 폭딜',dmg:45},
{name:'공포',icon:'😱',desc:'공포 — 적 ATK -50%',dmg:16},
{name:'역병',icon:'☠️',desc:'전염 DoT — 적 전이',dmg:14,dot:true},
{name:'피의 계약',icon:'📜',desc:'HP 30% 소모 — ATK 2배',buff:true,dmg:0},
{name:'네크로맨서',icon:'💀',desc:'죽은 적 부활 — 아군화',dmg:18},
{name:'암흑 결계',icon:'🔮',desc:'AoE 봉인 — 적 스킬 봉쇄',dmg:22,aoe:true},
{name:'영혼 수확',icon:'⚰️',desc:'처형 — HP 15% 이하 즉사',dmg:60}],
passives:[
{name:'흡혈 +25%',icon:'🩸',desc:'공격 데미지의 25% HP 회복'},
{name:'저주 강화',icon:'💀',desc:'저주 효과 50% 증가'},
{name:'암흑 적응',icon:'🖤',desc:'HP 낮을수록 마법 데미지 증가 (최대 +60%)'},
{name:'영혼 수집',icon:'👻',desc:'킬마다 ATK +5% 영구 누적 (최대 +30%)'},
{name:'고통 전이',icon:'😈',desc:'받는 피해 30%를 적에게 전이'},
{name:'불사의 의지',icon:'💜',desc:'치명상 시 HP 1로 생존 (1회)'}]},
힐러:{color:'#06b6d4',glow:'#06b6d4',weapon:'💚',bodyColor:'linear-gradient(180deg,#0f4a5c,#082d3d)',desc:'치유 전문가. 파티의 생명줄. 회복과 보조에 특화.',baseHP:90,baseATK:10,baseDEF:7,
skills:[
{name:'치유의 빛',icon:'💚',desc:'단일 대상 대량 힐',buff:true,dmg:0},
{name:'재생의 바람',icon:'🍃',desc:'파티 전체 힐',buff:true,dmg:0},
{name:'성스러운 불꽃',icon:'🔥',desc:'신성 데미지 — 언데드 특효',dmg:24},
{name:'보호막',icon:'🛡️',desc:'파티원 보호막 — 피해 흡수',buff:true,dmg:0},
{name:'정화',icon:'✨',desc:'디버프 제거 + 힐',buff:true,dmg:0},
{name:'빛의 심판',icon:'⚡',desc:'AoE 신성 공격',dmg:20,aoe:true},
{name:'부활',icon:'💛',desc:'전사한 파티원 부활',buff:true,dmg:0},
{name:'신성 화살',icon:'🏹',desc:'원거리 빛 공격',dmg:22},
{name:'축복의 오라',icon:'💫',desc:'파티 DEF +30%',buff:true,dmg:0},
{name:'천사의 강림',icon:'👼',desc:'무적+전체힐 — 궁극기',buff:true,dmg:0}],
passives:[
{name:'자동 힐',icon:'💚',desc:'파티원 HP 50% 이하 시 자동 힐'},
{name:'힐량 +30%',icon:'✨',desc:'모든 회복 효과 30% 증가'},
{name:'보호 본능',icon:'🛡️',desc:'아군 피격 시 DEF 버프 자동 부여'},
{name:'마나 재생',icon:'💜',desc:'매 턴 마나 15% 회복'},
{name:'정화 강화',icon:'🌟',desc:'정화 시 ATK +20% 버프 추가'},
{name:'생명의 유대',icon:'💞',desc:'파티원 HP 공유 — 피해 분산'}]}
};

const LOADING_TEXTS=[
'터벅터벅 걸어가는 중...','하염없이 걷는 중...','몬스터 탐색 중...','잠시 쉬는 중...',
'주변을 살피는 중...','검을 갈고 있는 중...','지도를 펼쳐보는 중...','이상한 소리에 귀 기울이는 중...',
'풀숲을 헤치는 중...','어둠 속을 더듬는 중...','발자국을 따라가는 중...','낡은 이정표를 읽는 중...',
'바위 뒤를 조심히 살피는 중...','나뭇가지를 부러뜨리며 전진 중...','허기진 배를 움켜쥐는 중...',
'횃불을 밝히는 중...','무기를 점검하는 중...','갈림길에서 고민하는 중...','수상한 동굴을 발견한 것 같은 중...',
'바람 냄새를 맡는 중...','먼 곳에서 비명이 들리는 중...','오래된 유적 앞에 서 있는 중...',
'물웅덩이에 비친 얼굴을 보는 중...','방어구를 조이는 중...','숨을 고르는 중...',
'나뭇잎 사이로 뭔가 움직이는 중...','조용히 숨어서 정찰하는 중...','동료를 떠올리며 걷는 중...',
'약초를 발견해서 줍는 중...','어디선가 연기 냄새가 나는 중...',
'벽에 새겨진 문양을 살피는 중...','돌멩이를 발로 차며 걷는 중...','갑옷에 묻은 먼지를 털어내는 중...',
'코앞이 안 보일 정도로 어두운 중...','멀리서 북소리가 들리는 중...','모닥불 흔적을 발견한 중...',
'낡은 해골 옆을 조심히 지나가는 중...','절벽 위에서 아래를 내려다보는 중...',
'이끼 낀 계단을 내려가는 중...','거미줄을 치우며 전진하는 중...',
'허공에 손을 뻗어 기운을 느끼는 중...','오래된 무덤 앞에서 멈춘 중...',
'누군가 남긴 낙서를 읽는 중...','부서진 갑옷 조각을 줍는 중...',
'이상한 꽃이 피어있는 길을 지나는 중...','멀리 성벽이 보이는 중...',
'늑대 울음소리에 긴장하는 중...','웅크리고 앉아 전략을 짜는 중...',
'떨어진 깃털을 주워 살피는 중...','어두운 터널에 진입하는 중...',
];

// ===== HUNT STORIES (preset) =====
const NORMAL_STORIES=[
{intro:'풀숲을 헤치며 나아가자 {enemy}이(가) 불쑥 나타났다.'},
{intro:'어둠 속에서 눈빛이 번뜩이더니 {enemy}이(가) 덮쳐왔다!'},
{intro:'바위 뒤에서 기다리고 있던 {enemy}과(와) 눈이 마주쳤다.'},
{intro:'길을 걷던 중 발밑에서 {enemy}이(가) 솟아올랐다!'},
{intro:'수상한 소리를 따라갔더니 {enemy}이(가) 진을 치고 있었다.'},
{intro:'뒤돌아보니 {enemy}이(가) 이미 코앞에 와 있었다.'},
{intro:'나뭇가지가 부러지는 소리와 함께 {enemy}이(가) 뛰어나왔다.'},
{intro:'안개 속에서 서서히 {enemy}의 윤곽이 드러났다.'},
{intro:'동굴 깊은 곳에서 {enemy}의 울음소리가 메아리쳤다.'},
{intro:'함정을 피했지만, 그 뒤에 {enemy}이(가) 기다리고 있었다.'},
{intro:'시체 더미 위에 앉아있던 {enemy}이(가) 천천히 고개를 들었다.'},
{intro:'갈림길에서 잠시 망설이자 {enemy}이(가) 기습했다!'},
{intro:'물웅덩이를 건너려는 순간 {enemy}이(가) 수면 위로 튀어올랐다.'},
{intro:'허름한 오두막 안에서 {enemy}이(가) 웅크리고 있었다.'},
{intro:'바람이 갑자기 멈추더니 {enemy}이(가) 나타났다.'},
{intro:'{enemy}의 발자국을 따라가다 보니 소굴에 도착했다.'},
{intro:'썩은 냄새를 맡고 경계했지만 이미 {enemy}의 영역이었다.'},
{intro:'높은 절벽 위에서 {enemy}이(가) 아래를 내려다보고 있었다.'},
{intro:'무너진 다리 건너편에서 {enemy}이(가) 으르렁거렸다.'},
{intro:'낙엽이 소용돌이치더니 그 속에서 {enemy}이(가) 나타났다!'},
{intro:'잠든 줄 알았던 {enemy}이(가) 눈을 번쩍 떴다.'},
{intro:'보물상자를 열었는데 안에서 {enemy}이(가) 튀어나왔다!'},
{intro:'폐허가 된 마을을 지나가자 {enemy}이(가) 길을 막았다.'},
{intro:'모닥불 흔적 주변을 살피다 {enemy}과(와) 조우했다.'},
{intro:'좁은 통로를 지나가려는데 {enemy}이(가) 앞을 가로막았다.'},
{intro:'벽면의 균열에서 {enemy}이(가) 스르르 기어나왔다.'},
{intro:'고요한 호숫가에 다다르자 {enemy}이(가) 물 밖으로 솟았다.'},
{intro:'나무 꼭대기에서 {enemy}이(가) 뛰어내렸다!'},
{intro:'고대의 제단 위에서 {enemy}이(가) 눈을 빛냈다.'},
{intro:'뼈가 흩어진 길을 걷다 {enemy}의 그림자를 발견했다.'},
{intro:'묘비 사이를 지나가자 {enemy}이(가) 땅에서 솟아올랐다.'},
{intro:'비명 소리를 듣고 달려가니 {enemy}이(가) 사냥 중이었다.'},
{intro:'부서진 수레 뒤에 숨어있던 {enemy}과(와) 마주쳤다.'},
{intro:'포도 넝쿨을 헤치자 {enemy}이(가) 이빨을 드러냈다.'},
{intro:'계곡 아래로 내려가자 {enemy}이(가) 기다린 듯 나타났다.'},
{intro:'탑 꼭대기에 올라서자 {enemy}이(가) 날아들었다!'},
{intro:'오래된 우물 안에서 {enemy}의 신음 소리가 들렸다.'},
{intro:'석양이 지는 벌판에서 {enemy}의 실루엣이 보였다.'},
{intro:'미로 같은 동굴을 헤매다 {enemy}의 둥지에 들어섰다.'},
{intro:'마법 함정이 발동하며 {enemy}을(를) 소환했다!'},
{intro:'강을 건너려는 순간 {enemy}이(가) 급류 속에서 나타났다.'},
{intro:'번개가 치자 그 빛 속에서 {enemy}의 모습이 드러났다.'},
{intro:'가시덤불 사이에서 {enemy}이(가) 으르렁거리고 있었다.'},
{intro:'해골이 가리키는 방향으로 가니 {enemy}이(가) 있었다.'},
{intro:'천장에 매달려 있던 {enemy}이(가) 머리 위로 떨어졌다!'},
{intro:'발밑 땅이 흔들리더니 {enemy}이(가) 뚫고 나왔다.'},
{intro:'연기 자욱한 전장터에서 {enemy}이(가) 서성거리고 있었다.'},
{intro:'밤하늘의 별이 사라지더니 {enemy}이(가) 앞을 막았다.'},
{intro:'절벽 끝에 몰렸을 때 {enemy}이(가) 다가왔다.'},
{intro:'이끼 낀 석상이 깨지며 그 안에서 {enemy}이(가) 나왔다!'},
{intro:'거대한 나무뿌리 아래에서 {enemy}이(가) 잠을 자고 있었다.'},
{intro:'공기가 차가워지더니 {enemy}이(가) 안개 속에서 걸어나왔다.'},
{intro:'돌다리를 건너는 순간 {enemy}이(가) 다리 아래에서 올라왔다!'},
{intro:'벌레 소리가 뚝 멈추자 {enemy}이(가) 모습을 드러냈다.'},
{intro:'비바람 속에서 {enemy}의 포효가 울려 퍼졌다.'},
{intro:'마을 사람들이 두려워하던 {enemy}과(와) 마침내 마주쳤다.'},
{intro:'축축한 지하도를 걷다 {enemy}에게 발견됐다!'},
{intro:'수정 광산 깊은 곳에서 {enemy}이(가) 빛을 반사하며 다가왔다.'},
{intro:'마법진이 빛나더니 {enemy}이(가) 소환됐다!'},
{intro:'새벽안개를 뚫고 {enemy}이(가) 천천히 접근했다.'},
{intro:'무기를 점검하려 멈춘 사이 {enemy}이(가) 덮쳤다!'},
{intro:'바닥에 그려진 핏자국을 따라가자 {enemy}이(가) 있었다.'},
{intro:'문을 열자마자 {enemy}이(가) 달려들었다!'},
{intro:'상인의 경고를 무시한 대가로 {enemy}과(와) 조우했다.'},
{intro:'풍차 안에서 이상한 소리가 들려 들어가니 {enemy}이(가) 있었다.'},
{intro:'얼어붙은 호수 위를 걷다 얼음 아래에서 {enemy}이(가) 보였다.'},
{intro:'폭포 뒤 비밀 공간에서 {enemy}이(가) 보물을 지키고 있었다.'},
{intro:'별빛이 사라진 밤, {enemy}의 눈만 어둠 속에서 빛났다.'},
{intro:'낡은 감옥의 철창을 열자 {enemy}이(가) 자유를 얻었다!'},
{intro:'부패한 숲의 중심에서 {enemy}이(가) 나무에 기대 쉬고 있었다.'},
{intro:'밧줄 다리가 끊어질 뻔한 순간 건너편에 {enemy}이(가)!'},
{intro:'마법서에 적힌 대로 주문을 읽자 {enemy}이(가) 깨어났다.'},
{intro:'동상처럼 서있던 것이 사실 {enemy}이었다!'},
{intro:'화산재가 날리는 길에서 {enemy}이(가) 용암 틈에서 나왔다.'},
{intro:'도서관 책장 뒤에서 {enemy}이(가) 숨어 있었다.'},
{intro:'종소리가 울리자 {enemy}이(가) 그림자에서 분리되어 나왔다!'},
{intro:'거울 속에서 {enemy}이(가) 튀어나왔다!'},
{intro:'옥수수밭을 지나가다 {enemy}의 기척을 느꼈다.'},
{intro:'성벽 위를 순찰하다 {enemy}이(가) 기어올라오는 걸 목격했다!'},
{intro:'지하 수로를 따라가니 {enemy}이(가) 물길을 막고 서 있었다.'},
{intro:'텐트에서 자려는 순간 {enemy}이(가) 천을 찢고 들어왔다!'},
{intro:'시계탑의 태엽이 멈추자 {enemy}이(가) 나타났다.'},
{intro:'뒤를 돌아보지 말라는 경고를 어겼더니 {enemy}이(가) 있었다.'},
{intro:'모래폭풍이 지나간 자리에 {enemy}이(가) 서 있었다.'},
{intro:'낡은 피아노에서 저절로 소리가 나더니 {enemy}이(가) 나타났다!'},
{intro:'우편함에서 이상한 편지를 꺼내자 {enemy}이(가) 등 뒤에!'},
{intro:'벽난로 불이 꺼지자 어둠 속에서 {enemy}이(가) 다가왔다.'},
{intro:'망가진 마차 안에서 {enemy}이(가) 뒹굴고 있었다.'},
{intro:'부서진 조각상의 눈이 빛나더니 {enemy}이(가) 실체화됐다!'},
{intro:'꽃밭 한가운데서 {enemy}이(가) 먹이를 찾고 있었다.'},
{intro:'구덩이에 빠졌는데 그 아래에 {enemy}이(가) 있었다!'},
{intro:'농부의 헛간 문을 열자 {enemy}이(가) 쏟아져 나왔다.'},
{intro:'사슬 끌리는 소리가 점점 가까워지더니 {enemy}이(가)!'},
{intro:'첫 번째 함정은 피했지만 두 번째에서 {enemy}을(를) 만났다.'},
{intro:'유리병에 담긴 메시지를 읽는 순간 {enemy}이(가) 습격했다!'},
{intro:'퀘스트 게시판 앞에서 {enemy}이(가) 현상금을 떼고 있었다.'},
];

const BOSS_STORIES=[
{intro:'땅이 울리고 하늘이 갈라졌다. {enemy}이(가) 강림한다!'},
{intro:'주변의 모든 소리가 사라졌다. {enemy}이(가) 깨어났다...'},
{intro:'공기가 무겁게 짓누른다. {enemy}의 압도적인 존재감이 느껴진다.'},
{intro:'어둠이 형체를 이루더니 {enemy}의 모습으로 변했다!'},
{intro:'대지가 갈라지고 그 틈에서 {enemy}이(가) 올라왔다!'},
{intro:'번개가 연달아 치더니 {enemy}이(가) 천둥과 함께 나타났다!'},
{intro:'피비린내가 진동한다. {enemy}이(가) 왕좌에 앉아 기다리고 있었다.'},
{intro:'벽화에 그려진 {enemy}이(가) 벽에서 튀어나왔다!'},
{intro:'제단의 봉인이 풀리며 {enemy}이(가) 부활했다!'},
{intro:'하늘에서 거대한 그림자가 드리우더니 {enemy}이(가) 착지했다!'},
{intro:'세계가 비틀거린다. {enemy}이(가) 차원의 틈을 열고 나타났다.'},
{intro:'시간이 멈춘 듯한 정적 속에서 {enemy}의 눈이 빛났다.'},
{intro:'네 번의 경고를 무시했다. 다섯 번째는 {enemy} 그 자체였다.'},
{intro:'용사의 무덤 앞에서 {enemy}이(가) 도전을 기다리고 있었다.'},
{intro:'마법 결계가 산산조각 나며 {enemy}이(가) 해방됐다!'},
{intro:'탑의 꼭대기에서 {enemy}이(가) 세상을 내려다보고 있었다.'},
{intro:'보름달이 피빛으로 물들자 {enemy}이(가) 포효했다!'},
{intro:'전설은 사실이었다. {enemy}이(가) 눈앞에 서 있다.'},
{intro:'지진이 멈추자 먼지 속에서 {enemy}의 실루엣이 보였다.'},
{intro:'마지막 문 너머에서 {enemy}이(가) 미소를 짓고 있었다.'},
];

const HUNT_TEMPLATES=[
{name:'어두운 숲',intro:['울창한 숲 속으로 발걸음을 옮겼다...','나뭇가지 사이로 불길한 눈빛이 번뜩인다.'],enemies:['고블린','숲 늑대','독버섯 정령'],boss:'숲의 수호자 엔트',bossEmoji:'🌲'},
{name:'잊혀진 동굴',intro:['습기 찬 동굴 깊숙이 들어섰다...','벽면에서 기묘한 빛이 새어나온다.'],enemies:['박쥐 떼','동굴 트롤','크리스탈 골렘'],boss:'심연의 거미 여왕',bossEmoji:'🕷️'},
{name:'고대 유적',intro:['무너진 신전의 잔해를 넘었다...','공기 중에 마력이 감돈다.'],enemies:['스켈레톤 병사','저주받은 석상','유령 마법사'],boss:'불멸의 리치 왕',bossEmoji:'💀'},
{name:'화산 지대',intro:['발밑에서 용암이 부글거린다...','열기가 피부를 태울 듯하다.'],enemies:['화염 도마뱀','용암 슬라임','불의 정령'],boss:'화염군주 이프리트',bossEmoji:'🔥'},
{name:'얼어붙은 설원',intro:['매서운 눈보라가 시야를 가린다...','발자국이 순식간에 눈에 묻힌다.'],enemies:['얼음 늑대','프로스트 골렘','눈보라 유령'],boss:'겨울왕 프리즈번',bossEmoji:'❄️'},
{name:'독의 늪지대',intro:['질퍽한 늪을 조심스레 걷는다...','독기 어린 안개가 피어오른다.'],enemies:['독 개구리','늪지 히드라','부패 좀비'],boss:'독룡 베노사우르',bossEmoji:'🐉'},
{name:'하늘의 탑',intro:['구름을 뚫고 솟은 탑에 올랐다...','바람이 귓가에 속삭인다.'],enemies:['하피','천둥 매','바람의 정령'],boss:'폭풍의 지배자 라이쿠',bossEmoji:'⚡'},
{name:'지하 감옥',intro:['쇠사슬 끌리는 소리가 울려퍼진다...','어둠 속에서 신음이 들린다.'],enemies:['감옥 쥐인간','탈옥 골렘','어둠 기사'],boss:'고문관 블러드메인',bossEmoji:'⛓️'},
{name:'버려진 광산',intro:['광산 수레의 녹슨 바퀴가 삐걱인다...','곡괭이 소리가 깊은 곳에서 울린다.'],enemies:['광산 드워프','보석 거미','폭발 박쥐'],boss:'광산왕 두린의 망령',bossEmoji:'⛏️'},
{name:'달빛 묘지',intro:['보름달 아래 묘비들이 줄지어 서있다...','땅 속에서 무언가 꿈틀거린다.'],enemies:['해골 궁수','구울','밴시'],boss:'죽음의 기사 모르가나',bossEmoji:'🌙'},
{name:'사막 오아시스',intro:['끝없는 모래사막을 건넌다...','신기루 너머 오아시스가 보인다.'],enemies:['사막 전갈','모래 웜','미라'],boss:'사막의 파라오 아누비스',bossEmoji:'🏜️'},
{name:'수정 동굴',intro:['형형색색 수정이 빛을 발한다...','공명하는 수정 소리가 귀를 울린다.'],enemies:['수정 박쥐','프리즘 슬라임','마나 흡수체'],boss:'수정룡 크리스탈리아',bossEmoji:'💎'}
];

const ITEM_PREFIX=['고대의','불타는','얼어붙은','저주받은','축복받은','신비한','피묻은','영원의'];
const ITEM_MATERIAL=['강철','미스릴','흑요석','드래곤','오리할콘','아다만티움'];
const ITEM_SUFFIX={weapon:['검','지팡이','활','도끼','총'],offhand:['방패','보조검','토템','서적'],helmet:['투구','왕관','두건','머리띠'],chest:['갑옷','로브','조끼','망토'],gloves:['장갑','건틀릿','손목보호대'],pants:['바지','레깅스','각반'],boots:['장화','부츠','샌들'],necklace:['목걸이','펜던트','초커'],ring1:['반지','밴드','인장'],ring2:['반지','밴드','인장']};
const ITEM_EMOJIS={weapon:['🗡️','🪄','🏹','🪓','🔫'],offhand:['🛡️','⚔️','🔮','📖'],helmet:['⛑️','👑','🎭','💎'],chest:['🛡️','🧥','👘','🧣'],gloves:['🧤','🥊','⚡'],pants:['👖','🩳','🦿'],boots:['👢','👟','🩴'],necklace:['📿','💎','⭐'],ring1:['💍','💫','🔵'],ring2:['💍','💫','🔵']};
const GRADE_WEIGHTS=[{g:'일반',w:45},{g:'매직',w:30},{g:'레어',w:15},{g:'유니크',w:8},{g:'에픽',w:2}];
const GRADE_COLORS={일반:'#ccc',매직:'#4a9eff',레어:'#ffd700',유니크:'#daa520',에픽:'#a855f7'};
const FLAVOR_TEXTS=['이 장비에서 알 수 없는 힘이 느껴진다.','오래된 전장의 기억이 서려있다.','제작자의 혼이 담긴 명품이다.','어둠 속에서 희미하게 빛난다.','손에 쥐면 전율이 느껴진다.','수많은 전투를 겪은 흔적이 있다.','신비로운 문양이 새겨져 있다.','전설 속 장인이 만들었다고 전해진다.'];

const LEVELUP_BUFFS=[
// 공격력
{name:'⚔️ 힘 +3',desc:'공격력 3 증가',apply:p=>{p.atk+=3}},
{name:'⚔️ 힘 +5',desc:'공격력 5 증가',apply:p=>{p.atk+=5}},
{name:'⚔️ 맹공',desc:'공격력 8 증가',apply:p=>{p.atk+=8}},
// 체력
{name:'❤️ 체력 +15',desc:'최대 HP 15 증가',apply:p=>{p.maxHP+=15;p.hp=Math.min(p.hp+15,p.maxHP)}},
{name:'❤️ 체력 +30',desc:'최대 HP 30 증가',apply:p=>{p.maxHP+=30;p.hp=Math.min(p.hp+30,p.maxHP)}},
{name:'❤️ 강인함',desc:'최대 HP 50 증가',apply:p=>{p.maxHP+=50;p.hp=Math.min(p.hp+50,p.maxHP)}},
// 방어력
{name:'🛡️ 방어 +2',desc:'방어력 2 증가',apply:p=>{p.def+=2}},
{name:'🛡️ 방어 +4',desc:'방어력 4 증가',apply:p=>{p.def+=4}},
{name:'🛡️ 철벽',desc:'방어력 7 증가',apply:p=>{p.def+=7}},
// 치명타
{name:'🎯 민첩 +3%',desc:'치명타 확률 3% 증가',apply:p=>{p.critBonus=(p.critBonus||0)+3}},
{name:'🎯 민첩 +5%',desc:'치명타 확률 5% 증가',apply:p=>{p.critBonus=(p.critBonus||0)+5}},
{name:'🎯 날렵함',desc:'치명타 확률 8% 증가',apply:p=>{p.critBonus=(p.critBonus||0)+8}},
// 공격속도
{name:'⚡ 공격속도 +1',desc:'공격속도 1 증가',apply:p=>{p.atkSpeed=(p.atkSpeed||0)+1}},
{name:'⚡ 공격속도 +2',desc:'공격속도 2 증가',apply:p=>{p.atkSpeed=(p.atkSpeed||0)+2}},
// 스킬 데미지
{name:'💜 마력 +5%',desc:'스킬 데미지 5% 증가',apply:p=>{p.skillDmgBonus=(p.skillDmgBonus||0)+5}},
{name:'💜 마력 +10%',desc:'스킬 데미지 10% 증가',apply:p=>{p.skillDmgBonus=(p.skillDmgBonus||0)+10}},
// 행운/골드
{name:'🍀 행운 +5%',desc:'아이템 드롭률 5% 증가',apply:p=>{p.luckBonus=(p.luckBonus||0)+5}},
{name:'💰 골드 수집 +10%',desc:'골드 획득량 10% 증가',apply:p=>{p.goldBonus=(p.goldBonus||0)+10}},
// 복합
{name:'🔥 전투 본능',desc:'ATK+3, 치명타+2%',apply:p=>{p.atk+=3;p.critBonus=(p.critBonus||0)+2}},
{name:'💪 생존 본능',desc:'HP+20, DEF+2',apply:p=>{p.maxHP+=20;p.hp=Math.min(p.hp+20,p.maxHP);p.def+=2}},
{name:'✨ 만능',desc:'ATK+2, DEF+2, HP+10',apply:p=>{p.atk+=2;p.def+=2;p.maxHP+=10;p.hp=Math.min(p.hp+10,p.maxHP)}},
];

const MISSIONS=[
{npc:'대장장이 모루스',avatar:'🔨',color:'#8B4513',dialogue:'용사여, 내 대장간에 쓸 재료가 부족하오. 모험 중에 광석을 찾아와 주시오!',reward:'💰 80 + 💎 5',gold:80,points:5},
{npc:'마법사 엘드린',avatar:'🧙',color:'#4B0082',dialogue:'고대 마법진의 잔재를 연구 중이오. 유적에서 마력 결정을 가져다 주시오.',reward:'💰 60 + 💎 8',gold:60,points:8},
{npc:'정찰병 카이',avatar:'🏹',color:'#2F4F4F',dialogue:'숲 외곽에 수상한 움직임이 포착됐습니다. 정찰을 부탁드립니다!',reward:'💰 50 + 💎 3',gold:50,points:3},
{npc:'주점주인 릴라',avatar:'🍺',color:'#8B008B',dialogue:'요즘 손님들이 이상한 소문을 퍼뜨리고 있어요. 진상을 알아봐 주세요~',reward:'💰 40 + 💎 10',gold:40,points:10}
];
